require 'forwardable'

require_relative 'containers/product/expiration/shared'
require_relative 'containers/product/expiration/example'
require_relative 'containers/product/shared'
require_relative 'containers/product/example'
require_relative 'containers/quote/shared'
require_relative 'containers/quote/example'
require_relative 'containers/leg/shared'
require_relative 'containers/leg/example'
